name: Python CI

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Python 버전 확인
        shell: bash -l {0}
        run: python --version

      - name: Miniconda 설정
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: finmate
          environment-file: environment.yml
          auto-activate-base: false

      - name: 패키지 확인
        shell: bash -l {0}
        run: pip list

      - name: pytest 실행
        run: |
          pytest
